<?php
//code to create a custom table in wordpress
global $wpdb;
$table = $wpdb->prefix . "ngo_profile"; 
$charset_collate = $wpdb->get_charset_collate();
$sql = "CREATE TABLE IF NOT EXISTS $table (
    `id` mediumint(9) NOT NULL AUTO_INCREMENT,
    `nguser_id` mediumint(9) NOT NULL,
    `cpname` varchar(20) NOT NULL,
    `email_id` text NOT NULL,
    `mobile_n` text NOT NULL,
    `reserve_cont` text NOT NULL,
    `fr_cont` text NOT NULL,
    `acc_cont` text NOT NULL,
    `ngo_mission` text NOT NULL,
    `ngo_vision` text NOT NULL,
    `ngo_story` text NOT NULL,
    `ngo_pan` text NOT NULL,
    `ngo_pan_reg_no` text NOT NULL,
    `ngo_pan_reg_date` text NOT NULL,
    `ngo_pan_doc` LONGBLOB NOT NULL,
    `ngo_tan` text NOT NULL,
    `ngo_tan_reg_no` text NOT NULL,
    `ngo_tan_reg_date` text NOT NULL,
    `ngo_tan_doc` LONGBLOB NOT NULL,
    `bank_name` text NOT NULL,
    `bank_b_add` char(255) NOT NULL,
    `acc_number` text NOT NULL,
    `acc_name` text NOT NULL,
    `micr_num` text NOT NULL,
    `acc_type` text NOT NULL,
    `swift_code` text NOT NULL,
    `ifsc_code` text NOT NULL,
    `nbank_name` text NOT NULL,
    `nbank_b_add` char(255) NOT NULL,
    `nacc_number` text NOT NULL,
    `nacc_name` text NOT NULL,
    `nmicr_num` text NOT NULL,
    `nacc_type` text NOT NULL,
    `nswift_code` text NOT NULL,
    `nifsc_code` text NOT NULL,
    `about_org` text NOT NULL,
    `org_name` text NOT NULL,
    `legal_name` text NOT NULL,
    `cpdesig` text NOT NULL,
    `website` text NOT NULL,
    `reg_add` text NOT NULL,
    `state` text NOT NULL, 
    `city` text NOT NULL,
    `last_year_expd` text NOT NULL,
    `last_year_income` text NOT NULL,
    `last_year_tourn` text NOT NULL,
    `no_of_bnfs` text NOT NULL,
    `a_tlv_number` text NOT NULL,
    `g_eighty_number` text NOT NULL,
    `g_eighty_dor` text NOT NULL,
    `g_eighty_doex` text NOT NULL,
    `g_eighty_reson_of_expire` text NOT NULL,
    `g_eighty_doc` LONGBLOB NOT NULL,
    `cause_for` text NOT NULL,
    `acroyn` text NOT NULL,
    `pin_number` text NOT NULL,
    `designation` text NOT NULL,
    `cp_eamil` text NOT NULL,
    `cp_landline` text NOT NULL,
    `cp_mobile` text NOT NULL,
    `contact_type` text NOT NULL,
    `contact_design` text NOT NULL,
    `contact_eamil` text NOT NULL,
    `contact_landline` text NOT NULL,
    `contact_mobile` text NOT NULL,
    `reserve_design` text NOT NULL,
    `reserve_eamil` text NOT NULL,
    `reserve_mobile` text NOT NULL,
    `reserve_landline` text NOT NULL,
    `fr_design` text NOT NULL,
    `fr_email` text NOT NULL,
    `fr_landline` text NOT NULL,
    `fr_mobile` text NOT NULL,
    `acc_design` text NOT NULL,
    `acc_eamil` text NOT NULL, 
    `acc_landline` text NOT NULL,
    `acc_mobile` text NOT NULL,
    `trust` text NOT NULL,
    `trust_dor` text NOT NULL,
    `trust_doc` LONGBLOB NOT NULL,
    `socity_name` text NOT NULL,
    `socity_reg_number` text NOT NULL,
    `socity_date_of_reg` text NOT NULL,
    `socity_doc` LONGBLOB NOT NULL,
    `section_eig_name` text NOT NULL,
    `secton_eig_reg_number` text NOT NULL,
    `section_eig_date_of_reg` text NOT NULL,
    `section_eig_date_of_exp` text NOT NULL,
    `section_eig_ren_of_exp` text NOT NULL,
    `section_eig_doc` LONGBLOB NOT NULL,
    `section_tlv_name` text NOT NULL,
    `secton_tlv_reg_number` text NOT NULL,
    `section_tlv_date_of_reg` text NOT NULL,
    `section_tlv_date_of_exp` text NOT NULL,
    `section_tlv_ren_of_exp` text NOT NULL,
    `section_tlv_doc` LONGBLOB NOT NULL,
    `section_fcra_name` text NOT NULL,
    `secton_fcra_reg_number` text NOT NULL,
    `section_fcra_date_of_reg` text NOT NULL,
    `section_fcra_date_of_exp` text NOT NULL,
    `section_fcra_ren_of_exp` text NOT NULL,
    `section_fcra_doc` LONGBLOB NOT NULL,
    `tel_number` text NOT NULL,
    `ngo_logo` LONGBLOB NOT NULL,
    `ngo_annul_report` LONGBLOB NOT NULL, 
    `approval_status` char(3) NOT NULL,
    `ngo_board_member` LONGBLOB NOT NULL,
    `audited_finance_doc` LONGBLOB NOT NULL,

UNIQUE (`id`)
) $charset_collate;";
require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
dbDelta( $sql );


?>
